### ISSUE TITLE
sysreqs

### ISSUE THREAD

**Issue by cole-brokamp** [cole-brokamp/rize#3]
TODO: implement automatic installation of system requirements using sysreqs from r-hub

For example,
```
curl https://sysreqs.r-hub.io/pkg/sp,sf/linux-x86_64-debian-gcc
```
will return
```
["libgeos-dev","libproj-dev","gdal-bin"]
```
and should be translated into 
```
apt-get install -y libgeos-dev libproj-dev gdal-bin
```

within the Dockerfile

**Comment by cole-brokamp** [comment]
do this inside R with `httr::GET()`

note that it is possible to get name of dependency as well as specific names for different platforms, e.g. macOS/brew, RPM, DEB

**Comment by nuest** [comment]
I can only recommend to do this, it works like a charm for our package `containerit`, see this internal function: https://github.com/o2r-project/containerit/blob/b6f8c71c3482fd48bd5e07e2925caee9cd890334/R/package-installation-methods.R#L356

We've also added a fallback since `sysreqs` can also [parse local `DESCRIPTION` files](https://github.com/o2r-project/containerit/blob/b6f8c71c3482fd48bd5e07e2925caee9cd890334/R/package-installation-methods.R#L271).

We don't have a timeline for publishing on CRAN yet, but if you'd be interested to collaborate on a function `{rize/containerit}::df_instruction_install(deps = ... platform = "DEB")`, let me know.

**Comment by cole-brokamp** [comment]
Thanks for the tip! I think I'll eventually add something similar only for DEB since that is what my base image relies on.
