### ISSUE TITLE
Issue with own packages

### ISSUE THREAD

**Issue by dmenne** [cole-brokamp/rize#4]
rize works nicely with a simple application without one of my own packages.

I have two packages, breathtestcore and breathteststan, both on CRAN and on github (dmenne/breathtestcore, dmenne/breathteststan). I tried to dockerize dmenne/breathtestshiny (not on CRAN).
This gives me an error message that breathtestcore cannot be found which I traced down to 

```
pkg_name = "breathtestcore"
pkg_d <- packageDescription(pkg_name)
is.cran <- !is.null(pkg_d$Repository) && pkg_d$Repository == 
  "CRAN"
is.github <- !is.null(pkg_d$GithubRepo)
```

Both are false, because there is no Repositor and GithubRepo in DESCRIPTION (but there is Remotes)

https://github.com/dmenne/breathtestcore/blob/master/DESCRIPTION

**Comment by dmenne** [comment]
I noted that I have to upload my own packages, an download these from Github/CRAN to get these fields correctly. I see the point, but maybe some better error message for this case would be nice.

**Comment by cole-brokamp** [comment]
Thanks for the feedback and for using rize.  You are correct, and I have also ran into this issue myself.  Currently, I make sure to push my own packages to Github (even if private) in order to get rize to correctly read them.

I will look into a way around this and also into making a more informative error message in the automagic package, which handles the package dependencies.

See also here: https://github.com/cole-brokamp/automagic/issues/1

**Comment by dmenne** [comment]
```
* DONE (breathtestcore)
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >= 
Calls: <Anonymous> ... dev_package_deps -> local_package_deps -> lapply -> FUN
Execution halted
The command '/bin/sh -c R -e "setwd('/srv/shiny-server/app'); automagic::automagic()"' returned a non-zero code: 1
```

Having got around the above, I am now stuck with this on. Most likely some problem with 

```
Suggests: 
  breathtestcore (>= 0.4.0), 
  breathteststan (>= 0.4.0),

```

(Same result on Windows and Ubuntu)

**Comment by dmenne** [comment]
Still unsolved and reproducable.
